### ISSUE TITLE
Settings Fragment closes on Screen rotation

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#589]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    

**Actual Behaviour**

When user is in Settings Fragment and rotate the screen, the settings fragment is destroyed and Events layout page is loaded.

**Expected Behaviour**

Settings fragment should withstand app rotation.

**Steps to reproduce it**

LogIn -> Select settings option from drawer -> Rotate the screen -> Event's page gets loaded.
![ezgif-4-ab1443eee8](https://user-images.githubusercontent.com/23634977/34928050-e9f28458-f9e0-11e7-9b9c-ab798e3a9af3.gif)

**LogCat for the issue**
```

OkHttp: --> GET https://open-event-api.herokuapp.com/v1/users/327/events?page[size]=0 http/1.1
D/OkHttp: --> END GET
D/OkHttp: <-- 200 OK https://open-event-api.herokuapp.com/v1/users/327/events?page[size]=0 (664ms)
D/OkHttp: Connection: keep-alive
D/OkHttp: Content-Type: application/vnd.api+json
D/OkHttp: Etag: 46d23668535421f2fa7b891b628453eb264ca55f
D/OkHttp: Server: gunicorn/19.7.1
D/OkHttp: Date: Mon, 15 Jan 2018 05:07:39 GMT
D/OkHttp: Access-Control-Allow-Origin: *
D/OkHttp: Via: 1.1 vegur
D/OkHttp: {"meta": {"count": 0}, "data": [], "jsonapi": {"version": "1.0"}, "links": {"self": "/v1/events?page%5Bsize%5D=0"}}
D/OkHttp: <-- END HTTP (115-byte body)
I/DatabaseRepository: Saved items of type class org.fossasia.openevent.app.common.data.models.Event in database
I/Logger: List of items successfully loaded with count: 0
I/art: Starting a blocking GC Explicit
I/art: Explicit concurrent mark sweep GC freed 8173(497KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 17MB/29MB, paused 660us total 61.718ms

```
**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Android version and Phone Model**

Moto G4 Plus
    
**Would you like to work on the issue?**

No

**Comment by Tilak-Shenoy** [comment]
Hi 
I would like to look upon this issue

**Comment by Masquerade0097** [comment]
@Tilak-Shenoy Please go ahead.

**Comment by iamareebjamal** [comment]
I think this is solved now. Please confirm @Masquerade0097

**Comment by Masquerade0097** [comment]
@iamareebjamal The issue is still there. EventList, Event Settings and Device Settings on rotating opens Dashboard.

**Comment by srv-twry** [comment]
Yes, it is still there. Fixing it.
