### ISSUE TITLE
Refresh snackbar displayed up twice when refreshed

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-orga-app#657]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When refreshed the "Refresh Complete" message pops up twice

**Expected Behaviour**

It should be displayed only once

**GIF of the issue**

![videotogif_2018 02 23_00 35 56](https://user-images.githubusercontent.com/16715499/36558747-04ba40f4-1832-11e8-9ebd-b4c5cbc4c2f7.gif)

**Would you like to work on the issue?**

YES

**Comment by mishuvs** [comment]
Hi @simarsingh24 
I am not able to reproduce the issue. Is it still happening?

**Comment by simarsingh24** [comment]
@mishuvs i am busy with my midsems, it may be possible that the issue has been resolved

**Comment by mishuvs** [comment]
@simarsingh24 Oh! I just noticed that the issue is not yet resolved. Don't know why it worked fine yesterday. 
Are you working on it?

**Comment by iamareebjamal** [comment]
@mishuvs @simarsingh24 Status?

**Comment by mishuvs** [comment]
I will comment when a PR is ready.
