### ISSUE TITLE
Unexpected behavior of Application.

### ISSUE THREAD

**Issue by ahsan44411** [fossasia/open-event-orga-app#844]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When the app goes in to landscape mode and comes back to portrait the application closes.

**Expected Behaviour**

When the app goes in to landscape mode and comes back the application should display portrait mode.

**LogCat for the issue**

03-26 19:33:21.964 12934-12934/org.fossasia.eventyay I/Activity_Manager: Timeline: Activity_idle id: android.os.BinderProxy@428bc608 time:112907590
03-26 19:33:27.024 12934-12967/org.fossasia.eventyay D/dalvikvm: GC_EXPLICIT freed 1082K, 8% free 14329K/15456K, paused 3ms+7ms, total 53ms
**03-26 19:33:30.374 12934-12934/org.fossasia.eventyay I/Logger: List of items successfully loaded with count: 11**
03-26 19:33:30.404 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.404 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.404 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.404 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.404 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.414 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.414 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.414 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.414 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.414 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.414 12934-12981/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Event From Disk on Thread RxCachedThreadScheduler-1
03-26 19:33:30.474 12934-12934/org.fossasia.eventyay D/dalvikvm: GC_FOR_ALLOC freed 614K, 7% free 14448K/15456K, paused 25ms, total 27ms
03-26 19:33:30.474 12934-12934/org.fossasia.eventyay I/dalvikvm-heap: Grow heap (frag case) to 20.120MB for 4096016-byte allocation
**03-26 19:33:30.734 12934-12934/org.fossasia.eventyay I/Logger: List of items successfully loaded with count: 11**
03-26 19:33:30.934 12934-12934/org.fossasia.eventyay I/Activity_Manager: Timeline: Activity_idle id: android.os.BinderProxy@428bc608 time:112916568
03-26 19:33:35.864 12934-12934/org.fossasia.eventyay D/dalvikvm: GC_EXPLICIT freed 740K, 6% free 18477K/19500K, paused 2ms+6ms, total 39ms
**03-26 19:33:35.874 12934-12934/org.fossasia.eventyay W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.**
03-26 19:33:35.874 12934-12934/org.fossasia.eventyay I/Process: Sending signal. PID: 12934 SIG: 9

**Android version and Phone Model**

Android Kitkat , API 19, Phone Sony Xperia T3
    

**Would you like to work on the issue?**

No, I won't, please give this to some one else.

**Comment by srv-twry** [comment]
@ahsan44411 This should have been resolved now. Can you check and confirm that it has been solved ? 
If yes, then close it.

**Comment by ahsan44411** [comment]
I'll check

**Comment by mishuvs** [comment]
@srv-twry I just checked. Although it doesn't always crashes the first time you perform this action, it does crash if performed repetitively (more than 2-3 times).
Thus, the issue persists.

**Comment by iamareebjamal** [comment]
This won't work in release apk. This is related to some memory leaks false alarms and issues. Hopefully they'll be fixed when we move to MVVM
